name: Bicep CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-bicep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.21.0
          inlineScript: |
            az version
            az account show
            az account set -s 996a2f3f-ee01-4ffd-9765-d2c3fc98f30a
            az deployment sub what-if -f main.bicep -l westus